### home 경로 테스트
GET http://localhost:8080
Authorization: Basic korea 123
### user 경로 테스트
GET http://localhost:8080/user
Authorization: Basic korea 123
### user 경로 테스트
GET http://localhost:8080/user/id/abcf